import React, { useState } from 'react';

export default function ReportViewer({ report, verdict }) {
  const [isOpen, setIsOpen] = useState(false);

  if (!report) return null;

  const downloadReport = () => {
    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `veri_byte_forensic_report_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-panel detail-card animate-fade-in">
      <div className="detail-card-header">
        <div className="detail-header-left">
          <span className="detail-icon">📋</span>
          <div>
            <h3>Official Forensic Analysis Report</h3>
            <p>Comprehensive audit record generated by Veri-Byte screening engine</p>
          </div>
        </div>
        <div className="detail-header-right">
          <button className="btn-primary btn-download" onClick={downloadReport}>
            <span>📥</span> Download Report (.md)
          </button>
          <button
            className="btn-secondary"
            onClick={() => setIsOpen(!isOpen)}
            style={{ marginLeft: '8px' }}
          >
            {isOpen ? '▲ Collapse' : '▼ Expand'}
          </button>
        </div>
      </div>

      {isOpen && (
        <div className="report-markdown-body animate-fade-in">
          <pre className="report-pre">{report}</pre>
        </div>
      )}
    </div>
  );
}
